apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
spec:
  containers:
    - name: app
      image: alpine
      command:
        - sleep
        - '3600'
      resources:
        requests:
          memory: "64Mi"
          cpu: "1000m"
  nodeSelector:
    disktype: ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-app-1
spec:
  containers:
    - name: app
      image: alpine
      command:
        - sleep
        - '3600'
      resources:
        requests:
          cpu: "1000m"
          memory: "64Mi"
  nodeSelector:
    disktype: ssd
