apiVersion: v1
kind: Pod
metadata:
  name: my-pv
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sh","-c","echo Hello Team, This is Persistent Volume Claim >> /output/success.txt"]
      volumeMounts:
        - name: my-pv
          mountPath: /output
  volumes:
    - name: my-pv
      persistentVolumeClaim:
        claimName: my-pvc
