apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    tier: frontend
spec:
  containers:
    - name: application1
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  labels:
    tier: frontend
spec:
  containers:
    - name: application2
      image: nginx
