apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes:
    - name: hostpath-vol
      hostPath:
        path: /home/vimalp/Kubernetes/practice/practicejune/section42/k8s_storage/
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/bash","-c","echo Hello Team, This is a sample file for HostVolume - $(date) >> /output/output.txt && sleep 3600"]
      volumeMounts:
        - name: hostpath-vol
          mountPath: /output
