apiVersion: v1
kind: Pod
metadata:
  name: frontend-1
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep","3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "6850m"
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-2
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep","3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "6250m"
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-3
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep","3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "6750m"
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-4
spec:
  containers:
    - name: frontend-4
      image: alpine
      command: ["sleep","3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "2750m"
