apiVersion: v1
kind: Pod
metadata:
  name: draining-node-test-pod2
  labels:
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  restartPolicy: OnFailure
