apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginxpod
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31011
      targetPort: nginxport
